# Generated by Django 4.2 on 2024-06-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
